abstract final class ProfileOptions {
  static const cities = <String>[
    'Barranquilla',
    'Bogotá',
    'Cali',
    'Cartagena',
    'Medellín',
    'Santa Marta',
    'Valledupar',
    'Bucaramanga',
    'Cúcuta',
    'Ibagué',
    'Manizales',
    'Pereira',
    'Armenia',
    'Popayán',
    'Pasto',
    'Túquerres',
    'Quibdó',
    'Montería',
    'Sincelejo',
    'Riohacha',
    'Santa Fe de Antioquia',
    'Envigado',
    'Sabaneta',
    'La Estrella',
    'Bello',
    'Copacabana',
    'Girardota',
    'Barbosa',
  ];

  static const semesters = <String>[
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '1 y 2',
    '2 y 3',
    '3 y 4',
    '4 y 5',
    '5 y 6',
    '6 y 7',
    '7 y 8',
    '8 y 9',
    '9 y 10',
  ];
}
